### PR TITLE
Added a Standard Score method.

### PR DESCRIPTION
**Pull request by awesomebjt**
Hi, I'm still learning Rust so if my implementation here doesn't gel with how you want your library to work, let me know if there's anything I should do differently. In a recent project (in a different language) I used standard scores. Even though it's a very simple formula, I thought others might find it convenient not to need to roll their own.

### CODE REVIEW

**Comment by JeffBelgum** [comment]
Thanks for the PR! It looks great! 

Where did the test cases come from?

I've also added a few commits, so can you please rebase your PR? (because I had to look it up myself just now: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

**Comment by awesomebjt** [comment]
Sure, I'll rebase and try again. The test cases came from running the same functions in Python 2.7 with the help of the "statistics" module.

**Comment by awesomebjt** [comment]
I followed the rebase directions and it seems to have worked.

**Comment by JeffBelgum** [comment]
Great, everything looks good.

**Pull request merged**
